{{- if .Values.gvisor.autoInstall.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "isola.gvisorInstaller.fullname" . }}
  labels:
    {{- include "isola.gvisorInstaller.labels" . | nindent 4 }}
{{- end }}
