/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Isola from "../../../../index.mjs";
/**
 * @example
 *     {
 *         name: "name"
 *     }
 */
export interface CreateSandboxRequest {
    /** Human-readable name for the sandbox */
    name: string;
    /** Container image to use for the sandbox */
    image?: string;
    /** Region where the sandbox should be deployed */
    region?: string;
    /** CPU cores to allocate (e.g., 0.5, 1, 2) */
    cpu?: number;
    /** Memory in GB to allocate */
    memory?: number;
    /** Disk space in GB to allocate */
    disk?: number;
    /** Number of GPUs to allocate */
    gpu?: number;
    /** Environment variables to set in the sandbox */
    env?: Record<string, string>;
    /** Labels to attach to the sandbox */
    labels?: Record<string, string>;
    /** Volumes to attach to the sandbox */
    volumes?: Isola.AttachedVolume[];
    /** Whether to start the sandbox automatically after creation */
    autoStart?: boolean;
}
