image:
  repository: isola-gw
  tag: "latest"

logLevel: info

# Namespace for sandbox pods
sandboxNamespace: isola-sandboxes

nodePort:
  enabled: false

kubernetes:
  namespace: "isola-sandboxes"
  runtimeClassName: ""

storage:
  enabled: false
  bucketUrl: ""
  # Credentials (read automatically by go-cloud from standard env vars)
  awsAccessKeyId: ""
  awsSecretAccessKey: ""
