/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as errors from "../../errors/index.mjs";
export class BadGatewayError extends errors.IsolaError {
    constructor(body, rawResponse) {
        super({
            message: "BadGatewayError",
            statusCode: 502,
            body: body,
            rawResponse: rawResponse,
        });
        Object.setPrototypeOf(this, BadGatewayError.prototype);
    }
}
