# This file was auto-generated by Fern from our API Definition.

from ..core.client_wrapper import SyncClientWrapper
import typing
from ..core.request_options import RequestOptions
from ..types.health_response import HealthResponse
from ..core.pydantic_utilities import parse_obj_as
from json.decoder import JSONDecodeError
from ..core.api_error import ApiError
from ..types.ready_response import ReadyResponse
from ..core.client_wrapper import AsyncClientWrapper


class HealthClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def check(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HealthResponse:
        """
        Returns the health status of the gateway and its components

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HealthResponse
            Service is healthy

        Examples
        --------
        from isola import Isola

        client = Isola(
            api_key="YOUR_API_KEY",
        )
        client.health.check()
        """
        _response = self._client_wrapper.httpx_client.request(
            "health",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    HealthResponse,
                    parse_obj_as(
                        type_=HealthResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def readiness_check(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ReadyResponse:
        """
        Returns whether the service is ready to accept requests

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ReadyResponse
            Service is ready

        Examples
        --------
        from isola import Isola

        client = Isola(
            api_key="YOUR_API_KEY",
        )
        client.health.readiness_check()
        """
        _response = self._client_wrapper.httpx_client.request(
            "ready",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    ReadyResponse,
                    parse_obj_as(
                        type_=ReadyResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)


class AsyncHealthClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def check(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HealthResponse:
        """
        Returns the health status of the gateway and its components

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HealthResponse
            Service is healthy

        Examples
        --------
        import asyncio

        from isola import AsyncIsola

        client = AsyncIsola(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.health.check()


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "health",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    HealthResponse,
                    parse_obj_as(
                        type_=HealthResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def readiness_check(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ReadyResponse:
        """
        Returns whether the service is ready to accept requests

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ReadyResponse
            Service is ready

        Examples
        --------
        import asyncio

        from isola import AsyncIsola

        client = AsyncIsola(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.health.readiness_check()


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "ready",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    ReadyResponse,
                    parse_obj_as(
                        type_=ReadyResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)
