"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IsolaClient = void 0;
const Client_js_1 = require("./api/resources/health/client/Client.js");
const Client_js_2 = require("./api/resources/sandboxes/client/Client.js");
const Client_js_3 = require("./api/resources/execution/client/Client.js");
const Client_js_4 = require("./api/resources/files/client/Client.js");
class IsolaClient {
    constructor(_options = {}) {
        this._options = _options;
    }
    get health() {
        var _a;
        return ((_a = this._health) !== null && _a !== void 0 ? _a : (this._health = new Client_js_1.Health(this._options)));
    }
    get sandboxes() {
        var _a;
        return ((_a = this._sandboxes) !== null && _a !== void 0 ? _a : (this._sandboxes = new Client_js_2.Sandboxes(this._options)));
    }
    get execution() {
        var _a;
        return ((_a = this._execution) !== null && _a !== void 0 ? _a : (this._execution = new Client_js_3.Execution(this._options)));
    }
    get files() {
        var _a;
        return ((_a = this._files) !== null && _a !== void 0 ? _a : (this._files = new Client_js_4.Files(this._options)));
    }
}
exports.IsolaClient = IsolaClient;
