"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IsolaEnvironment = void 0;
exports.IsolaEnvironment = {
    Default: "http://localhost:8080",
};
