"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Sandboxes = void 0;
const environments = __importStar(require("../../../../environments.js"));
const core = __importStar(require("../../../../core/index.js"));
const Isola = __importStar(require("../../../index.js"));
const url_join_1 = __importDefault(require("url-join"));
const errors = __importStar(require("../../../../errors/index.js"));
/**
 * Sandbox lifecycle management
 */
class Sandboxes {
    constructor(_options = {}) {
        this._options = _options;
    }
    /**
     * Returns a paginated list of sandboxes, optionally filtered by state
     *
     * @param {Isola.ListSandboxesRequest} request
     * @param {Sandboxes.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Isola.BadRequestError}
     * @throws {@link Isola.UnauthorizedError}
     * @throws {@link Isola.InternalServerError}
     *
     * @example
     *     await client.sandboxes.listSandboxes({
     *         state: "pending",
     *         limit: 1,
     *         offset: 1
     *     })
     */
    listSandboxes(request = {}, requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__listSandboxes(request, requestOptions));
    }
    __listSandboxes() {
        return __awaiter(this, arguments, void 0, function* (request = {}, requestOptions) {
            var _a, _b;
            const { state, limit, offset } = request;
            const _queryParams = {};
            if (state != null) {
                _queryParams["state"] = state;
            }
            if (limit != null) {
                _queryParams["limit"] = limit.toString();
            }
            if (offset != null) {
                _queryParams["offset"] = offset.toString();
            }
            const _response = yield core.fetcher({
                url: (0, url_join_1.default)((_b = (_a = (yield core.Supplier.get(this._options.baseUrl))) !== null && _a !== void 0 ? _a : (yield core.Supplier.get(this._options.environment))) !== null && _b !== void 0 ? _b : environments.IsolaEnvironment.Default, "api/v1/sandboxes"),
                method: "GET",
                headers: Object.assign(Object.assign({ "X-Fern-Language": "JavaScript", "X-Fern-Runtime": core.RUNTIME.type, "X-Fern-Runtime-Version": core.RUNTIME.version }, (yield this._getCustomAuthorizationHeaders())), requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.headers),
                contentType: "application/json",
                queryParameters: _queryParams,
                requestType: "json",
                timeoutMs: (requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.timeoutInSeconds) != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                maxRetries: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.maxRetries,
                abortSignal: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.abortSignal,
            });
            if (_response.ok) {
                return { data: _response.body, rawResponse: _response.rawResponse };
            }
            if (_response.error.reason === "status-code") {
                switch (_response.error.statusCode) {
                    case 400:
                        throw new Isola.BadRequestError(_response.error.body, _response.rawResponse);
                    case 401:
                        throw new Isola.UnauthorizedError(_response.error.body, _response.rawResponse);
                    case 500:
                        throw new Isola.InternalServerError(_response.error.body, _response.rawResponse);
                    default:
                        throw new errors.IsolaError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.body,
                            rawResponse: _response.rawResponse,
                        });
                }
            }
            switch (_response.error.reason) {
                case "non-json":
                    throw new errors.IsolaError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.rawBody,
                        rawResponse: _response.rawResponse,
                    });
                case "timeout":
                    throw new errors.IsolaTimeoutError("Timeout exceeded when calling GET /api/v1/sandboxes.");
                case "unknown":
                    throw new errors.IsolaError({
                        message: _response.error.errorMessage,
                        rawResponse: _response.rawResponse,
                    });
            }
        });
    }
    /**
     * Creates a new sandbox with the specified configuration
     *
     * @param {Isola.CreateSandboxRequest} request
     * @param {Sandboxes.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Isola.BadRequestError}
     * @throws {@link Isola.UnauthorizedError}
     * @throws {@link Isola.InternalServerError}
     *
     * @example
     *     await client.sandboxes.createSandbox({
     *         name: "name"
     *     })
     */
    createSandbox(request, requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__createSandbox(request, requestOptions));
    }
    __createSandbox(request, requestOptions) {
        return __awaiter(this, void 0, void 0, function* () {
            var _a, _b;
            const _response = yield core.fetcher({
                url: (0, url_join_1.default)((_b = (_a = (yield core.Supplier.get(this._options.baseUrl))) !== null && _a !== void 0 ? _a : (yield core.Supplier.get(this._options.environment))) !== null && _b !== void 0 ? _b : environments.IsolaEnvironment.Default, "api/v1/sandboxes"),
                method: "POST",
                headers: Object.assign(Object.assign({ "X-Fern-Language": "JavaScript", "X-Fern-Runtime": core.RUNTIME.type, "X-Fern-Runtime-Version": core.RUNTIME.version }, (yield this._getCustomAuthorizationHeaders())), requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.headers),
                contentType: "application/json",
                requestType: "json",
                body: request,
                timeoutMs: (requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.timeoutInSeconds) != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                maxRetries: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.maxRetries,
                abortSignal: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.abortSignal,
            });
            if (_response.ok) {
                return { data: _response.body, rawResponse: _response.rawResponse };
            }
            if (_response.error.reason === "status-code") {
                switch (_response.error.statusCode) {
                    case 400:
                        throw new Isola.BadRequestError(_response.error.body, _response.rawResponse);
                    case 401:
                        throw new Isola.UnauthorizedError(_response.error.body, _response.rawResponse);
                    case 500:
                        throw new Isola.InternalServerError(_response.error.body, _response.rawResponse);
                    default:
                        throw new errors.IsolaError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.body,
                            rawResponse: _response.rawResponse,
                        });
                }
            }
            switch (_response.error.reason) {
                case "non-json":
                    throw new errors.IsolaError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.rawBody,
                        rawResponse: _response.rawResponse,
                    });
                case "timeout":
                    throw new errors.IsolaTimeoutError("Timeout exceeded when calling POST /api/v1/sandboxes.");
                case "unknown":
                    throw new errors.IsolaError({
                        message: _response.error.errorMessage,
                        rawResponse: _response.rawResponse,
                    });
            }
        });
    }
    /**
     * Returns details of a specific sandbox by ID
     *
     * @param {string} id - Unique identifier of the sandbox (UUID)
     * @param {Sandboxes.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Isola.UnauthorizedError}
     * @throws {@link Isola.NotFoundError}
     * @throws {@link Isola.InternalServerError}
     *
     * @example
     *     await client.sandboxes.getSandbox("550e8400-e29b-41d4-a716-446655440000")
     */
    getSandbox(id, requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__getSandbox(id, requestOptions));
    }
    __getSandbox(id, requestOptions) {
        return __awaiter(this, void 0, void 0, function* () {
            var _a, _b;
            const _response = yield core.fetcher({
                url: (0, url_join_1.default)((_b = (_a = (yield core.Supplier.get(this._options.baseUrl))) !== null && _a !== void 0 ? _a : (yield core.Supplier.get(this._options.environment))) !== null && _b !== void 0 ? _b : environments.IsolaEnvironment.Default, `api/v1/sandboxes/${encodeURIComponent(id)}`),
                method: "GET",
                headers: Object.assign(Object.assign({ "X-Fern-Language": "JavaScript", "X-Fern-Runtime": core.RUNTIME.type, "X-Fern-Runtime-Version": core.RUNTIME.version }, (yield this._getCustomAuthorizationHeaders())), requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.headers),
                contentType: "application/json",
                requestType: "json",
                timeoutMs: (requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.timeoutInSeconds) != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                maxRetries: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.maxRetries,
                abortSignal: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.abortSignal,
            });
            if (_response.ok) {
                return { data: _response.body, rawResponse: _response.rawResponse };
            }
            if (_response.error.reason === "status-code") {
                switch (_response.error.statusCode) {
                    case 401:
                        throw new Isola.UnauthorizedError(_response.error.body, _response.rawResponse);
                    case 404:
                        throw new Isola.NotFoundError(_response.error.body, _response.rawResponse);
                    case 500:
                        throw new Isola.InternalServerError(_response.error.body, _response.rawResponse);
                    default:
                        throw new errors.IsolaError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.body,
                            rawResponse: _response.rawResponse,
                        });
                }
            }
            switch (_response.error.reason) {
                case "non-json":
                    throw new errors.IsolaError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.rawBody,
                        rawResponse: _response.rawResponse,
                    });
                case "timeout":
                    throw new errors.IsolaTimeoutError("Timeout exceeded when calling GET /api/v1/sandboxes/{id}.");
                case "unknown":
                    throw new errors.IsolaError({
                        message: _response.error.errorMessage,
                        rawResponse: _response.rawResponse,
                    });
            }
        });
    }
    /**
     * Terminates and deletes a sandbox
     *
     * @param {string} id - Unique identifier of the sandbox (UUID)
     * @param {Isola.TerminateSandboxRequest} request
     * @param {Sandboxes.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Isola.UnauthorizedError}
     * @throws {@link Isola.NotFoundError}
     * @throws {@link Isola.InternalServerError}
     *
     * @example
     *     await client.sandboxes.terminateSandbox("550e8400-e29b-41d4-a716-446655440000", {
     *         force: true
     *     })
     */
    terminateSandbox(id, request = {}, requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__terminateSandbox(id, request, requestOptions));
    }
    __terminateSandbox(id_1) {
        return __awaiter(this, arguments, void 0, function* (id, request = {}, requestOptions) {
            var _a, _b;
            const { force } = request;
            const _queryParams = {};
            if (force != null) {
                _queryParams["force"] = force.toString();
            }
            const _response = yield core.fetcher({
                url: (0, url_join_1.default)((_b = (_a = (yield core.Supplier.get(this._options.baseUrl))) !== null && _a !== void 0 ? _a : (yield core.Supplier.get(this._options.environment))) !== null && _b !== void 0 ? _b : environments.IsolaEnvironment.Default, `api/v1/sandboxes/${encodeURIComponent(id)}`),
                method: "DELETE",
                headers: Object.assign(Object.assign({ "X-Fern-Language": "JavaScript", "X-Fern-Runtime": core.RUNTIME.type, "X-Fern-Runtime-Version": core.RUNTIME.version }, (yield this._getCustomAuthorizationHeaders())), requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.headers),
                contentType: "application/json",
                queryParameters: _queryParams,
                requestType: "json",
                timeoutMs: (requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.timeoutInSeconds) != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                maxRetries: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.maxRetries,
                abortSignal: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.abortSignal,
            });
            if (_response.ok) {
                return { data: undefined, rawResponse: _response.rawResponse };
            }
            if (_response.error.reason === "status-code") {
                switch (_response.error.statusCode) {
                    case 401:
                        throw new Isola.UnauthorizedError(_response.error.body, _response.rawResponse);
                    case 404:
                        throw new Isola.NotFoundError(_response.error.body, _response.rawResponse);
                    case 500:
                        throw new Isola.InternalServerError(_response.error.body, _response.rawResponse);
                    default:
                        throw new errors.IsolaError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.body,
                            rawResponse: _response.rawResponse,
                        });
                }
            }
            switch (_response.error.reason) {
                case "non-json":
                    throw new errors.IsolaError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.rawBody,
                        rawResponse: _response.rawResponse,
                    });
                case "timeout":
                    throw new errors.IsolaTimeoutError("Timeout exceeded when calling DELETE /api/v1/sandboxes/{id}.");
                case "unknown":
                    throw new errors.IsolaError({
                        message: _response.error.errorMessage,
                        rawResponse: _response.rawResponse,
                    });
            }
        });
    }
    _getCustomAuthorizationHeaders() {
        return __awaiter(this, void 0, void 0, function* () {
            const apiKeyValue = yield core.Supplier.get(this._options.apiKey);
            return { "X-API-Key": apiKeyValue };
        });
    }
}
exports.Sandboxes = Sandboxes;
