/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Response from confirming an upload
 */
export interface ConfirmUploadResponse {
    /** Whether the file was transferred successfully */
    success: boolean;
    /** Path where the file was placed in the sandbox */
    path: string;
    /** Size of the file in bytes */
    size: number;
}
