/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Response from command execution
 */
export interface ExecuteCommandResponse {
    /** Standard output from the command */
    stdout: string;
    /** Standard error from the command */
    stderr: string;
    /** Exit code of the command (0 = success) */
    exitCode: number;
}
