/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Response from file download
 */
export interface FileDownloadResponse {
    /** Path of the downloaded file */
    path: string;
    /** Size of the file in bytes */
    size: number;
    /** Base64-encoded file content */
    content: string;
}
