/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Current state of the sandbox
 */
export type SandboxState = "pending" | "starting" | "running" | "terminating" | "stopped" | "error" | "unknown";
export declare const SandboxState: {
    readonly Pending: "pending";
    readonly Starting: "starting";
    readonly Running: "running";
    readonly Terminating: "terminating";
    readonly Stopped: "stopped";
    readonly Error: "error";
    readonly Unknown: "unknown";
};
