/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Isola from "../index.js";
/**
 * Paginated list of sandboxes
 */
export interface SandboxList {
    items: Isola.Sandbox[];
    /** Total number of sandboxes matching the filter */
    total: number;
    /** Maximum items per page */
    limit: number;
    /** Number of items skipped */
    offset: number;
}
