"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.SandboxState = void 0;
exports.SandboxState = {
    Pending: "pending",
    Starting: "starting",
    Running: "running",
    Terminating: "terminating",
    Stopped: "stopped",
    Error: "error",
    Unknown: "unknown",
};
