/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Response containing presigned upload URL
 */
export interface UploadUrlResponse {
    /** Presigned URL to upload the file to */
    upload_url: string;
    /** Unique identifier for this upload session */
    upload_id: string;
    /** Seconds until the presigned URL expires */
    expires_in: number;
}
