/**
 * This file was auto-generated by Fern from our API Definition.
 */
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
import * as environments from "../../../../environments.mjs";
import * as core from "../../../../core/index.mjs";
import * as Isola from "../../../index.mjs";
import urlJoin from "url-join";
import * as errors from "../../../../errors/index.mjs";
/**
 * File operations (upload/download)
 */
export class Files {
    constructor(_options = {}) {
        this._options = _options;
    }
    /**
     * Downloads a file from the sandbox. Returns base64-encoded content.
     * Maximum file size is 5MB. For larger files, use chunked download.
     *
     * @param {string} id - Unique identifier of the sandbox (UUID)
     * @param {Isola.DownloadFileRequest} request
     * @param {Files.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Isola.BadRequestError}
     * @throws {@link Isola.UnauthorizedError}
     * @throws {@link Isola.NotFoundError}
     * @throws {@link Isola.ConflictError}
     * @throws {@link Isola.ContentTooLargeError}
     * @throws {@link Isola.InternalServerError}
     * @throws {@link Isola.BadGatewayError}
     *
     * @example
     *     await client.files.downloadFile("550e8400-e29b-41d4-a716-446655440000", {
     *         path: "/home/user/output.txt"
     *     })
     */
    downloadFile(id, request, requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__downloadFile(id, request, requestOptions));
    }
    __downloadFile(id, request, requestOptions) {
        return __awaiter(this, void 0, void 0, function* () {
            var _a, _b;
            const { path } = request;
            const _queryParams = {};
            _queryParams["path"] = path;
            const _response = yield core.fetcher({
                url: urlJoin((_b = (_a = (yield core.Supplier.get(this._options.baseUrl))) !== null && _a !== void 0 ? _a : (yield core.Supplier.get(this._options.environment))) !== null && _b !== void 0 ? _b : environments.IsolaEnvironment.Default, `api/v1/sandboxes/${encodeURIComponent(id)}/files`),
                method: "GET",
                headers: Object.assign(Object.assign({ "X-Fern-Language": "JavaScript", "X-Fern-Runtime": core.RUNTIME.type, "X-Fern-Runtime-Version": core.RUNTIME.version }, (yield this._getCustomAuthorizationHeaders())), requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.headers),
                contentType: "application/json",
                queryParameters: _queryParams,
                requestType: "json",
                timeoutMs: (requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.timeoutInSeconds) != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                maxRetries: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.maxRetries,
                abortSignal: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.abortSignal,
            });
            if (_response.ok) {
                return { data: _response.body, rawResponse: _response.rawResponse };
            }
            if (_response.error.reason === "status-code") {
                switch (_response.error.statusCode) {
                    case 400:
                        throw new Isola.BadRequestError(_response.error.body, _response.rawResponse);
                    case 401:
                        throw new Isola.UnauthorizedError(_response.error.body, _response.rawResponse);
                    case 404:
                        throw new Isola.NotFoundError(_response.error.body, _response.rawResponse);
                    case 409:
                        throw new Isola.ConflictError(_response.error.body, _response.rawResponse);
                    case 413:
                        throw new Isola.ContentTooLargeError(_response.error.body, _response.rawResponse);
                    case 500:
                        throw new Isola.InternalServerError(_response.error.body, _response.rawResponse);
                    case 502:
                        throw new Isola.BadGatewayError(_response.error.body, _response.rawResponse);
                    default:
                        throw new errors.IsolaError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.body,
                            rawResponse: _response.rawResponse,
                        });
                }
            }
            switch (_response.error.reason) {
                case "non-json":
                    throw new errors.IsolaError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.rawBody,
                        rawResponse: _response.rawResponse,
                    });
                case "timeout":
                    throw new errors.IsolaTimeoutError("Timeout exceeded when calling GET /api/v1/sandboxes/{id}/files.");
                case "unknown":
                    throw new errors.IsolaError({
                        message: _response.error.errorMessage,
                        rawResponse: _response.rawResponse,
                    });
            }
        });
    }
    /**
     * Uploads a file to the sandbox. For files under 5MB, uploads directly.
     * For larger files, use the presigned URL flow (upload-url + confirm endpoints).
     *
     * @param {string} id
     * @param {Isola.UploadFileRequest} request
     * @param {Files.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Isola.BadRequestError}
     * @throws {@link Isola.UnauthorizedError}
     * @throws {@link Isola.NotFoundError}
     * @throws {@link Isola.ConflictError}
     * @throws {@link Isola.InternalServerError}
     * @throws {@link Isola.NotImplementedError}
     * @throws {@link Isola.BadGatewayError}
     *
     * @example
     *     await client.files.uploadFile("550e8400-e29b-41d4-a716-446655440000", {
     *         file: fs.createReadStream("/path/to/your/file"),
     *         path: "path"
     *     })
     */
    uploadFile(id, request, requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__uploadFile(id, request, requestOptions));
    }
    __uploadFile(id, request, requestOptions) {
        return __awaiter(this, void 0, void 0, function* () {
            var _a, _b;
            const _request = yield core.newFormData();
            yield _request.appendFile("file", request.file);
            _request.append("path", request.path);
            const _maybeEncodedRequest = yield _request.getRequest();
            const _response = yield core.fetcher({
                url: urlJoin((_b = (_a = (yield core.Supplier.get(this._options.baseUrl))) !== null && _a !== void 0 ? _a : (yield core.Supplier.get(this._options.environment))) !== null && _b !== void 0 ? _b : environments.IsolaEnvironment.Default, `api/v1/sandboxes/${encodeURIComponent(id)}/files`),
                method: "POST",
                headers: Object.assign(Object.assign(Object.assign({ "X-Fern-Language": "JavaScript", "X-Fern-Runtime": core.RUNTIME.type, "X-Fern-Runtime-Version": core.RUNTIME.version }, (yield this._getCustomAuthorizationHeaders())), _maybeEncodedRequest.headers), requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.headers),
                requestType: "file",
                duplex: _maybeEncodedRequest.duplex,
                body: _maybeEncodedRequest.body,
                timeoutMs: (requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.timeoutInSeconds) != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                maxRetries: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.maxRetries,
                abortSignal: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.abortSignal,
            });
            if (_response.ok) {
                return { data: _response.body, rawResponse: _response.rawResponse };
            }
            if (_response.error.reason === "status-code") {
                switch (_response.error.statusCode) {
                    case 400:
                        throw new Isola.BadRequestError(_response.error.body, _response.rawResponse);
                    case 401:
                        throw new Isola.UnauthorizedError(_response.error.body, _response.rawResponse);
                    case 404:
                        throw new Isola.NotFoundError(_response.error.body, _response.rawResponse);
                    case 409:
                        throw new Isola.ConflictError(_response.error.body, _response.rawResponse);
                    case 500:
                        throw new Isola.InternalServerError(_response.error.body, _response.rawResponse);
                    case 501:
                        throw new Isola.NotImplementedError(_response.error.body, _response.rawResponse);
                    case 502:
                        throw new Isola.BadGatewayError(_response.error.body, _response.rawResponse);
                    default:
                        throw new errors.IsolaError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.body,
                            rawResponse: _response.rawResponse,
                        });
                }
            }
            switch (_response.error.reason) {
                case "non-json":
                    throw new errors.IsolaError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.rawBody,
                        rawResponse: _response.rawResponse,
                    });
                case "timeout":
                    throw new errors.IsolaTimeoutError("Timeout exceeded when calling POST /api/v1/sandboxes/{id}/files.");
                case "unknown":
                    throw new errors.IsolaError({
                        message: _response.error.errorMessage,
                        rawResponse: _response.rawResponse,
                    });
            }
        });
    }
    /**
     * Generates a presigned URL for uploading large files directly to object storage.
     * After uploading to the presigned URL, call the confirm endpoint to trigger
     * the file transfer to the sandbox.
     *
     * @param {string} id - Unique identifier of the sandbox (UUID)
     * @param {Isola.UploadUrlRequest} request
     * @param {Files.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Isola.BadRequestError}
     * @throws {@link Isola.UnauthorizedError}
     * @throws {@link Isola.NotFoundError}
     * @throws {@link Isola.ConflictError}
     * @throws {@link Isola.InternalServerError}
     * @throws {@link Isola.NotImplementedError}
     *
     * @example
     *     await client.files.generateUploadUrl("550e8400-e29b-41d4-a716-446655440000", {
     *         path: "/home/user/large-file.zip",
     *         filename: "large-file.zip"
     *     })
     */
    generateUploadUrl(id, request, requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__generateUploadUrl(id, request, requestOptions));
    }
    __generateUploadUrl(id, request, requestOptions) {
        return __awaiter(this, void 0, void 0, function* () {
            var _a, _b;
            const _response = yield core.fetcher({
                url: urlJoin((_b = (_a = (yield core.Supplier.get(this._options.baseUrl))) !== null && _a !== void 0 ? _a : (yield core.Supplier.get(this._options.environment))) !== null && _b !== void 0 ? _b : environments.IsolaEnvironment.Default, `api/v1/sandboxes/${encodeURIComponent(id)}/files/upload-url`),
                method: "POST",
                headers: Object.assign(Object.assign({ "X-Fern-Language": "JavaScript", "X-Fern-Runtime": core.RUNTIME.type, "X-Fern-Runtime-Version": core.RUNTIME.version }, (yield this._getCustomAuthorizationHeaders())), requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.headers),
                contentType: "application/json",
                requestType: "json",
                body: request,
                timeoutMs: (requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.timeoutInSeconds) != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                maxRetries: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.maxRetries,
                abortSignal: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.abortSignal,
            });
            if (_response.ok) {
                return { data: _response.body, rawResponse: _response.rawResponse };
            }
            if (_response.error.reason === "status-code") {
                switch (_response.error.statusCode) {
                    case 400:
                        throw new Isola.BadRequestError(_response.error.body, _response.rawResponse);
                    case 401:
                        throw new Isola.UnauthorizedError(_response.error.body, _response.rawResponse);
                    case 404:
                        throw new Isola.NotFoundError(_response.error.body, _response.rawResponse);
                    case 409:
                        throw new Isola.ConflictError(_response.error.body, _response.rawResponse);
                    case 500:
                        throw new Isola.InternalServerError(_response.error.body, _response.rawResponse);
                    case 501:
                        throw new Isola.NotImplementedError(_response.error.body, _response.rawResponse);
                    default:
                        throw new errors.IsolaError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.body,
                            rawResponse: _response.rawResponse,
                        });
                }
            }
            switch (_response.error.reason) {
                case "non-json":
                    throw new errors.IsolaError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.rawBody,
                        rawResponse: _response.rawResponse,
                    });
                case "timeout":
                    throw new errors.IsolaTimeoutError("Timeout exceeded when calling POST /api/v1/sandboxes/{id}/files/upload-url.");
                case "unknown":
                    throw new errors.IsolaError({
                        message: _response.error.errorMessage,
                        rawResponse: _response.rawResponse,
                    });
            }
        });
    }
    /**
     * Confirms a large file upload after the file has been uploaded to the presigned URL.
     * Triggers the sandbox agent to download the file from object storage.
     *
     * @param {string} id - Unique identifier of the sandbox (UUID)
     * @param {Isola.ConfirmUploadRequest} request
     * @param {Files.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Isola.BadRequestError}
     * @throws {@link Isola.UnauthorizedError}
     * @throws {@link Isola.NotFoundError}
     * @throws {@link Isola.ConflictError}
     * @throws {@link Isola.InternalServerError}
     * @throws {@link Isola.NotImplementedError}
     * @throws {@link Isola.BadGatewayError}
     *
     * @example
     *     await client.files.confirmUpload("550e8400-e29b-41d4-a716-446655440000", {
     *         upload_id: "upload_id",
     *         filename: "filename",
     *         path: "path"
     *     })
     */
    confirmUpload(id, request, requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__confirmUpload(id, request, requestOptions));
    }
    __confirmUpload(id, request, requestOptions) {
        return __awaiter(this, void 0, void 0, function* () {
            var _a, _b;
            const _response = yield core.fetcher({
                url: urlJoin((_b = (_a = (yield core.Supplier.get(this._options.baseUrl))) !== null && _a !== void 0 ? _a : (yield core.Supplier.get(this._options.environment))) !== null && _b !== void 0 ? _b : environments.IsolaEnvironment.Default, `api/v1/sandboxes/${encodeURIComponent(id)}/files/confirm`),
                method: "POST",
                headers: Object.assign(Object.assign({ "X-Fern-Language": "JavaScript", "X-Fern-Runtime": core.RUNTIME.type, "X-Fern-Runtime-Version": core.RUNTIME.version }, (yield this._getCustomAuthorizationHeaders())), requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.headers),
                contentType: "application/json",
                requestType: "json",
                body: request,
                timeoutMs: (requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.timeoutInSeconds) != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                maxRetries: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.maxRetries,
                abortSignal: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.abortSignal,
            });
            if (_response.ok) {
                return { data: _response.body, rawResponse: _response.rawResponse };
            }
            if (_response.error.reason === "status-code") {
                switch (_response.error.statusCode) {
                    case 400:
                        throw new Isola.BadRequestError(_response.error.body, _response.rawResponse);
                    case 401:
                        throw new Isola.UnauthorizedError(_response.error.body, _response.rawResponse);
                    case 404:
                        throw new Isola.NotFoundError(_response.error.body, _response.rawResponse);
                    case 409:
                        throw new Isola.ConflictError(_response.error.body, _response.rawResponse);
                    case 500:
                        throw new Isola.InternalServerError(_response.error.body, _response.rawResponse);
                    case 501:
                        throw new Isola.NotImplementedError(_response.error.body, _response.rawResponse);
                    case 502:
                        throw new Isola.BadGatewayError(_response.error.body, _response.rawResponse);
                    default:
                        throw new errors.IsolaError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.body,
                            rawResponse: _response.rawResponse,
                        });
                }
            }
            switch (_response.error.reason) {
                case "non-json":
                    throw new errors.IsolaError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.rawBody,
                        rawResponse: _response.rawResponse,
                    });
                case "timeout":
                    throw new errors.IsolaTimeoutError("Timeout exceeded when calling POST /api/v1/sandboxes/{id}/files/confirm.");
                case "unknown":
                    throw new errors.IsolaError({
                        message: _response.error.errorMessage,
                        rawResponse: _response.rawResponse,
                    });
            }
        });
    }
    _getCustomAuthorizationHeaders() {
        return __awaiter(this, void 0, void 0, function* () {
            const apiKeyValue = yield core.Supplier.get(this._options.apiKey);
            return { "X-API-Key": apiKeyValue };
        });
    }
}
