/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "../../../../environments.mjs";
import * as core from "../../../../core/index.mjs";
import * as Isola from "../../../index.mjs";
export declare namespace Files {
    interface Options {
        environment?: core.Supplier<environments.IsolaEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey?: core.Supplier<string | undefined>;
    }
    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}
/**
 * File operations (upload/download)
 */
export declare class Files {
    protected readonly _options: Files.Options;
    constructor(_options?: Files.Options);
    /**
     * Downloads a file from the sandbox. Returns base64-encoded content.
     * Maximum file size is 5MB. For larger files, use chunked download.
     *
     * @param {string} id - Unique identifier of the sandbox (UUID)
     * @param {Isola.DownloadFileRequest} request
     * @param {Files.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Isola.BadRequestError}
     * @throws {@link Isola.UnauthorizedError}
     * @throws {@link Isola.NotFoundError}
     * @throws {@link Isola.ConflictError}
     * @throws {@link Isola.ContentTooLargeError}
     * @throws {@link Isola.InternalServerError}
     * @throws {@link Isola.BadGatewayError}
     *
     * @example
     *     await client.files.downloadFile("550e8400-e29b-41d4-a716-446655440000", {
     *         path: "/home/user/output.txt"
     *     })
     */
    downloadFile(id: string, request: Isola.DownloadFileRequest, requestOptions?: Files.RequestOptions): core.HttpResponsePromise<Isola.FileDownloadResponse>;
    private __downloadFile;
    /**
     * Uploads a file to the sandbox. For files under 5MB, uploads directly.
     * For larger files, use the presigned URL flow (upload-url + confirm endpoints).
     *
     * @param {string} id
     * @param {Isola.UploadFileRequest} request
     * @param {Files.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Isola.BadRequestError}
     * @throws {@link Isola.UnauthorizedError}
     * @throws {@link Isola.NotFoundError}
     * @throws {@link Isola.ConflictError}
     * @throws {@link Isola.InternalServerError}
     * @throws {@link Isola.NotImplementedError}
     * @throws {@link Isola.BadGatewayError}
     *
     * @example
     *     await client.files.uploadFile("550e8400-e29b-41d4-a716-446655440000", {
     *         file: fs.createReadStream("/path/to/your/file"),
     *         path: "path"
     *     })
     */
    uploadFile(id: string, request: Isola.UploadFileRequest, requestOptions?: Files.RequestOptions): core.HttpResponsePromise<Isola.FileUploadResponse>;
    private __uploadFile;
    /**
     * Generates a presigned URL for uploading large files directly to object storage.
     * After uploading to the presigned URL, call the confirm endpoint to trigger
     * the file transfer to the sandbox.
     *
     * @param {string} id - Unique identifier of the sandbox (UUID)
     * @param {Isola.UploadUrlRequest} request
     * @param {Files.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Isola.BadRequestError}
     * @throws {@link Isola.UnauthorizedError}
     * @throws {@link Isola.NotFoundError}
     * @throws {@link Isola.ConflictError}
     * @throws {@link Isola.InternalServerError}
     * @throws {@link Isola.NotImplementedError}
     *
     * @example
     *     await client.files.generateUploadUrl("550e8400-e29b-41d4-a716-446655440000", {
     *         path: "/home/user/large-file.zip",
     *         filename: "large-file.zip"
     *     })
     */
    generateUploadUrl(id: string, request: Isola.UploadUrlRequest, requestOptions?: Files.RequestOptions): core.HttpResponsePromise<Isola.UploadUrlResponse>;
    private __generateUploadUrl;
    /**
     * Confirms a large file upload after the file has been uploaded to the presigned URL.
     * Triggers the sandbox agent to download the file from object storage.
     *
     * @param {string} id - Unique identifier of the sandbox (UUID)
     * @param {Isola.ConfirmUploadRequest} request
     * @param {Files.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Isola.BadRequestError}
     * @throws {@link Isola.UnauthorizedError}
     * @throws {@link Isola.NotFoundError}
     * @throws {@link Isola.ConflictError}
     * @throws {@link Isola.InternalServerError}
     * @throws {@link Isola.NotImplementedError}
     * @throws {@link Isola.BadGatewayError}
     *
     * @example
     *     await client.files.confirmUpload("550e8400-e29b-41d4-a716-446655440000", {
     *         upload_id: "upload_id",
     *         filename: "filename",
     *         path: "path"
     *     })
     */
    confirmUpload(id: string, request: Isola.ConfirmUploadRequest, requestOptions?: Files.RequestOptions): core.HttpResponsePromise<Isola.ConfirmUploadResponse>;
    private __confirmUpload;
    protected _getCustomAuthorizationHeaders(): Promise<{
        "X-API-Key": string | undefined;
    }>;
}
