{{- if .Values.global.namespaces.createControlPlane }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespaces.controlPlaneName }}
  labels:
    name: {{ .Values.global.namespaces.controlPlaneName }}
    environment: {{ .Values.global.environment }}
    app.kubernetes.io/name: isola-control-plane
    app.kubernetes.io/part-of: isola-platform
    app.kubernetes.io/managed-by: helm
---
{{- end }}
{{- if .Values.global.namespaces.createSandboxes }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespaces.sandboxesName }}
  labels:
    name: {{ .Values.global.namespaces.sandboxesName }}
    environment: {{ .Values.global.environment }}
    app.kubernetes.io/name: isola-sandboxes
    app.kubernetes.io/part-of: isola-platform
    app.kubernetes.io/managed-by: helm
{{- end }}
