apiVersion: v1
kind: Service
metadata:
  name: {{ include "isola.operator.fullname" . }}-metrics
  labels:
    {{- include "isola.operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.operator.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "isola.operator.selectorLabels" . | nindent 4 }}
