{{- if .Values.operator.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "isola.operator.fullname" . }}-metrics
  labels:
    {{- include "isola.operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: {{ .Values.operator.metrics.port }}
    targetPort: metrics
    protocol: TCP
  selector:
    {{- include "isola.operator.selectorLabels" . | nindent 4 }}
{{- end }}
