apiVersion: v1
kind: Service
metadata:
  name: {{ include "isola.operator.fullname" . }}-metrics
  labels:
    {{- include "isola.operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.operator.metrics.service.type }}
  ports:
    - port: {{ .Values.operator.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
      {{- if and (eq .Values.operator.metrics.service.type "NodePort") .Values.operator.metrics.service.nodePort }}
      nodePort: {{ .Values.operator.metrics.service.nodePort }}
      {{- end }}
  selector:
    {{- include "isola.operator.selectorLabels" . | nindent 4 }}
