{{- if .Values.sandboxNamespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "isola.sandboxNamespace" . }}
  labels:
    {{- include "isola.sandbox.labels" . | nindent 4 }}
{{- end }}
