{{- if .Values.operator.sandboxPdb.enabled }}
# Since sandbox pods are effectively singletons, disrupting them (maxUnavailable > 0)
# could mean lost progress (no high availability "by design")
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: isola-sandbox
  namespace: {{ include "isola.sandboxNamespace" . }}
  labels:
    {{- include "isola.operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: sandbox
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: isola-sandbox
      app.kubernetes.io/managed-by: isola-operator
  maxUnavailable: {{ .Values.operator.sandboxPdb.maxUnavailable | default 0 }}
{{- end }}
