{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "isola.operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "isola.operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
    {{- with .Values.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "isola.operator.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
{{- end }}
