{{- if .Values.operator.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "isola.operator.fullname" . }}
  labels:
    {{- include "isola.operator.labels" . | nindent 4 }}
    {{- with .Values.operator.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "isola.operator.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    {{- with .Values.operator.serviceMonitor.interval }}
    interval: {{ . }}
    {{- end }}
    {{- with .Values.operator.serviceMonitor.scrapeTimeout }}
    scrapeTimeout: {{ . }}
    {{- end }}
    {{- with .Values.operator.serviceMonitor.relabelings }}
    relabelings:
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.operator.serviceMonitor.metricRelabelings }}
    metricRelabelings:
      {{- toYaml . | nindent 4 }}
    {{- end }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
{{- end }}
