/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "../../../../environments.mjs";
import * as core from "../../../../core/index.mjs";
import * as Isola from "../../../index.mjs";
export declare namespace Sandboxes {
    interface Options {
        environment?: core.Supplier<environments.IsolaEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey?: core.Supplier<string | undefined>;
    }
    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}
/**
 * Sandbox lifecycle management
 */
export declare class Sandboxes {
    protected readonly _options: Sandboxes.Options;
    constructor(_options?: Sandboxes.Options);
    /**
     * Returns a paginated list of sandboxes, optionally filtered by state
     *
     * @param {Isola.ListSandboxesRequest} request
     * @param {Sandboxes.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Isola.BadRequestError}
     * @throws {@link Isola.UnauthorizedError}
     * @throws {@link Isola.InternalServerError}
     *
     * @example
     *     await client.sandboxes.listSandboxes({
     *         state: "pending",
     *         limit: 1,
     *         offset: 1
     *     })
     */
    listSandboxes(request?: Isola.ListSandboxesRequest, requestOptions?: Sandboxes.RequestOptions): core.HttpResponsePromise<Isola.SandboxList>;
    private __listSandboxes;
    /**
     * Creates a new sandbox with the specified configuration
     *
     * @param {Isola.CreateSandboxRequest} request
     * @param {Sandboxes.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Isola.BadRequestError}
     * @throws {@link Isola.UnauthorizedError}
     * @throws {@link Isola.InternalServerError}
     *
     * @example
     *     await client.sandboxes.createSandbox({
     *         name: "name"
     *     })
     */
    createSandbox(request: Isola.CreateSandboxRequest, requestOptions?: Sandboxes.RequestOptions): core.HttpResponsePromise<Isola.Sandbox>;
    private __createSandbox;
    /**
     * Returns details of a specific sandbox by ID
     *
     * @param {string} id - Unique identifier of the sandbox (UUID)
     * @param {Sandboxes.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Isola.UnauthorizedError}
     * @throws {@link Isola.NotFoundError}
     * @throws {@link Isola.InternalServerError}
     *
     * @example
     *     await client.sandboxes.getSandbox("550e8400-e29b-41d4-a716-446655440000")
     */
    getSandbox(id: string, requestOptions?: Sandboxes.RequestOptions): core.HttpResponsePromise<Isola.Sandbox>;
    private __getSandbox;
    /**
     * Terminates and deletes a sandbox
     *
     * @param {string} id - Unique identifier of the sandbox (UUID)
     * @param {Isola.TerminateSandboxRequest} request
     * @param {Sandboxes.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Isola.UnauthorizedError}
     * @throws {@link Isola.NotFoundError}
     * @throws {@link Isola.InternalServerError}
     *
     * @example
     *     await client.sandboxes.terminateSandbox("550e8400-e29b-41d4-a716-446655440000", {
     *         force: true
     *     })
     */
    terminateSandbox(id: string, request?: Isola.TerminateSandboxRequest, requestOptions?: Sandboxes.RequestOptions): core.HttpResponsePromise<void>;
    private __terminateSandbox;
    protected _getCustomAuthorizationHeaders(): Promise<{
        "X-API-Key": string | undefined;
    }>;
}
