/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         command: "python script.py"
 *     }
 */
export interface ExecuteCommandRequest {
    /** Shell command to execute */
    command: string;
}
