# This file was auto-generated by Fern from our API Definition.

import typing
from ..core.client_wrapper import SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.file_download_response import FileDownloadResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.pydantic_utilities import parse_obj_as
from ..errors.bad_request_error import BadRequestError
from ..types.error_response import ErrorResponse
from ..errors.unauthorized_error import UnauthorizedError
from ..errors.not_found_error import NotFoundError
from ..errors.conflict_error import ConflictError
from ..errors.content_too_large_error import ContentTooLargeError
from ..errors.internal_server_error import InternalServerError
from ..errors.bad_gateway_error import BadGatewayError
from json.decoder import JSONDecodeError
from ..core.api_error import ApiError
from .. import core
from ..types.file_upload_response import FileUploadResponse
from ..errors.not_implemented_error import NotImplementedError
from ..types.upload_url_response import UploadUrlResponse
from ..types.confirm_upload_response import ConfirmUploadResponse
from ..core.client_wrapper import AsyncClientWrapper

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class FilesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def download_file(
        self,
        id: str,
        *,
        path: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FileDownloadResponse:
        """
        Downloads a file from the sandbox. Returns base64-encoded content.
        Maximum file size is 5MB. For larger files, use chunked download.

        Parameters
        ----------
        id : str
            Unique identifier of the sandbox (UUID)

        path : str
            Path to the file in the sandbox

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FileDownloadResponse
            File downloaded successfully

        Examples
        --------
        from isola import Isola

        client = Isola(
            api_key="YOUR_API_KEY",
        )
        client.files.download_file(
            id="550e8400-e29b-41d4-a716-446655440000",
            path="/home/user/output.txt",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/sandboxes/{jsonable_encoder(id)}/files",
            method="GET",
            params={
                "path": path,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    FileDownloadResponse,
                    parse_obj_as(
                        type_=FileDownloadResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 409:
                raise ConflictError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 413:
                raise ContentTooLargeError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 502:
                raise BadGatewayError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def upload_file(
        self,
        id: str,
        *,
        file: core.File,
        path: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FileUploadResponse:
        """
        Uploads a file to the sandbox. For files under 5MB, uploads directly.
        For larger files, use the presigned URL flow (upload-url + confirm endpoints).

        Parameters
        ----------
        id : str
            Unique identifier of the sandbox (UUID)

        file : core.File
            See core.File for more documentation

        path : str
            Target path in the sandbox

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FileUploadResponse
            File uploaded successfully

        Examples
        --------
        from isola import Isola

        client = Isola(
            api_key="YOUR_API_KEY",
        )
        client.files.upload_file(
            id="550e8400-e29b-41d4-a716-446655440000",
            path="path",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/sandboxes/{jsonable_encoder(id)}/files",
            method="POST",
            data={
                "path": path,
            },
            files={
                "file": file,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    FileUploadResponse,
                    parse_obj_as(
                        type_=FileUploadResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 409:
                raise ConflictError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 501:
                raise NotImplementedError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 502:
                raise BadGatewayError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def generate_upload_url(
        self,
        id: str,
        *,
        path: str,
        filename: str,
        content_type: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UploadUrlResponse:
        """
        Generates a presigned URL for uploading large files directly to object storage.
        After uploading to the presigned URL, call the confirm endpoint to trigger
        the file transfer to the sandbox.

        Parameters
        ----------
        id : str
            Unique identifier of the sandbox (UUID)

        path : str
            Target path in the sandbox where the file will be placed

        filename : str
            Name of the file being uploaded

        content_type : typing.Optional[str]
            MIME type of the file

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UploadUrlResponse
            Presigned URL generated successfully

        Examples
        --------
        from isola import Isola

        client = Isola(
            api_key="YOUR_API_KEY",
        )
        client.files.generate_upload_url(
            id="550e8400-e29b-41d4-a716-446655440000",
            path="/home/user/large-file.zip",
            filename="large-file.zip",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/sandboxes/{jsonable_encoder(id)}/files/upload-url",
            method="POST",
            json={
                "path": path,
                "filename": filename,
                "content_type": content_type,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    UploadUrlResponse,
                    parse_obj_as(
                        type_=UploadUrlResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 409:
                raise ConflictError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 501:
                raise NotImplementedError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def confirm_upload(
        self,
        id: str,
        *,
        upload_id: str,
        filename: str,
        path: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ConfirmUploadResponse:
        """
        Confirms a large file upload after the file has been uploaded to the presigned URL.
        Triggers the sandbox agent to download the file from object storage.

        Parameters
        ----------
        id : str
            Unique identifier of the sandbox (UUID)

        upload_id : str
            Upload ID from the upload-url response

        filename : str
            Name of the uploaded file

        path : str
            Target path in the sandbox

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConfirmUploadResponse
            Upload confirmed and file transferred to sandbox

        Examples
        --------
        from isola import Isola

        client = Isola(
            api_key="YOUR_API_KEY",
        )
        client.files.confirm_upload(
            id="550e8400-e29b-41d4-a716-446655440000",
            upload_id="upload_id",
            filename="filename",
            path="path",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/sandboxes/{jsonable_encoder(id)}/files/confirm",
            method="POST",
            json={
                "upload_id": upload_id,
                "filename": filename,
                "path": path,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    ConfirmUploadResponse,
                    parse_obj_as(
                        type_=ConfirmUploadResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 409:
                raise ConflictError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 501:
                raise NotImplementedError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 502:
                raise BadGatewayError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)


class AsyncFilesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def download_file(
        self,
        id: str,
        *,
        path: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FileDownloadResponse:
        """
        Downloads a file from the sandbox. Returns base64-encoded content.
        Maximum file size is 5MB. For larger files, use chunked download.

        Parameters
        ----------
        id : str
            Unique identifier of the sandbox (UUID)

        path : str
            Path to the file in the sandbox

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FileDownloadResponse
            File downloaded successfully

        Examples
        --------
        import asyncio

        from isola import AsyncIsola

        client = AsyncIsola(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.files.download_file(
                id="550e8400-e29b-41d4-a716-446655440000",
                path="/home/user/output.txt",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/sandboxes/{jsonable_encoder(id)}/files",
            method="GET",
            params={
                "path": path,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    FileDownloadResponse,
                    parse_obj_as(
                        type_=FileDownloadResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 409:
                raise ConflictError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 413:
                raise ContentTooLargeError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 502:
                raise BadGatewayError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def upload_file(
        self,
        id: str,
        *,
        file: core.File,
        path: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FileUploadResponse:
        """
        Uploads a file to the sandbox. For files under 5MB, uploads directly.
        For larger files, use the presigned URL flow (upload-url + confirm endpoints).

        Parameters
        ----------
        id : str
            Unique identifier of the sandbox (UUID)

        file : core.File
            See core.File for more documentation

        path : str
            Target path in the sandbox

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FileUploadResponse
            File uploaded successfully

        Examples
        --------
        import asyncio

        from isola import AsyncIsola

        client = AsyncIsola(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.files.upload_file(
                id="550e8400-e29b-41d4-a716-446655440000",
                path="path",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/sandboxes/{jsonable_encoder(id)}/files",
            method="POST",
            data={
                "path": path,
            },
            files={
                "file": file,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    FileUploadResponse,
                    parse_obj_as(
                        type_=FileUploadResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 409:
                raise ConflictError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 501:
                raise NotImplementedError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 502:
                raise BadGatewayError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def generate_upload_url(
        self,
        id: str,
        *,
        path: str,
        filename: str,
        content_type: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UploadUrlResponse:
        """
        Generates a presigned URL for uploading large files directly to object storage.
        After uploading to the presigned URL, call the confirm endpoint to trigger
        the file transfer to the sandbox.

        Parameters
        ----------
        id : str
            Unique identifier of the sandbox (UUID)

        path : str
            Target path in the sandbox where the file will be placed

        filename : str
            Name of the file being uploaded

        content_type : typing.Optional[str]
            MIME type of the file

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UploadUrlResponse
            Presigned URL generated successfully

        Examples
        --------
        import asyncio

        from isola import AsyncIsola

        client = AsyncIsola(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.files.generate_upload_url(
                id="550e8400-e29b-41d4-a716-446655440000",
                path="/home/user/large-file.zip",
                filename="large-file.zip",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/sandboxes/{jsonable_encoder(id)}/files/upload-url",
            method="POST",
            json={
                "path": path,
                "filename": filename,
                "content_type": content_type,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    UploadUrlResponse,
                    parse_obj_as(
                        type_=UploadUrlResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 409:
                raise ConflictError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 501:
                raise NotImplementedError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def confirm_upload(
        self,
        id: str,
        *,
        upload_id: str,
        filename: str,
        path: str,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ConfirmUploadResponse:
        """
        Confirms a large file upload after the file has been uploaded to the presigned URL.
        Triggers the sandbox agent to download the file from object storage.

        Parameters
        ----------
        id : str
            Unique identifier of the sandbox (UUID)

        upload_id : str
            Upload ID from the upload-url response

        filename : str
            Name of the uploaded file

        path : str
            Target path in the sandbox

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ConfirmUploadResponse
            Upload confirmed and file transferred to sandbox

        Examples
        --------
        import asyncio

        from isola import AsyncIsola

        client = AsyncIsola(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.files.confirm_upload(
                id="550e8400-e29b-41d4-a716-446655440000",
                upload_id="upload_id",
                filename="filename",
                path="path",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/sandboxes/{jsonable_encoder(id)}/files/confirm",
            method="POST",
            json={
                "upload_id": upload_id,
                "filename": filename,
                "path": path,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    ConfirmUploadResponse,
                    parse_obj_as(
                        type_=ConfirmUploadResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 409:
                raise ConflictError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 501:
                raise NotImplementedError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 502:
                raise BadGatewayError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)
