/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         path: "/home/user/output.txt"
 *     }
 */
export interface DownloadFileRequest {
    /**
     * Path to the file in the sandbox
     */
    path: string;
}
