/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as fs from "fs";
/**
 * @example
 *     {
 *         file: fs.createReadStream("/path/to/your/file"),
 *         path: "path"
 *     }
 */
export interface UploadFileRequest {
    file: File | fs.ReadStream | Blob;
    /** Target path in the sandbox */
    path: string;
}
