"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IsolaTimeoutError = void 0;
class IsolaTimeoutError extends Error {
    constructor(message) {
        super(message);
        Object.setPrototypeOf(this, IsolaTimeoutError.prototype);
    }
}
exports.IsolaTimeoutError = IsolaTimeoutError;
