# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing_extensions
from ..core.serialization import FieldMetadata
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class AttachedVolume(UniversalBaseModel):
    """
    A volume attached to the sandbox
    """

    volume_id: typing_extensions.Annotated[str, FieldMetadata(alias="volumeId")] = (
        pydantic.Field()
    )
    """
    ID of the volume to attach
    """

    mount_path: typing_extensions.Annotated[str, FieldMetadata(alias="mountPath")] = (
        pydantic.Field()
    )
    """
    Path where the volume is mounted in the sandbox
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
