# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing_extensions
from ..core.serialization import FieldMetadata
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class ExecuteCommandResponse(UniversalBaseModel):
    """
    Response from command execution
    """

    stdout: str = pydantic.Field()
    """
    Standard output from the command
    """

    stderr: str = pydantic.Field()
    """
    Standard error from the command
    """

    exit_code: typing_extensions.Annotated[int, FieldMetadata(alias="exitCode")] = (
        pydantic.Field()
    )
    """
    Exit code of the command (0 = success)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
