# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class FileDownloadResponse(UniversalBaseModel):
    """
    Response from file download
    """

    path: str = pydantic.Field()
    """
    Path of the downloaded file
    """

    size: int = pydantic.Field()
    """
    Size of the file in bytes
    """

    content: str = pydantic.Field()
    """
    Base64-encoded file content
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
