# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class FileUploadResponse(UniversalBaseModel):
    """
    Response from file upload
    """

    success: bool = pydantic.Field()
    """
    Whether the upload was successful
    """

    path: str = pydantic.Field()
    """
    Path where the file was uploaded
    """

    size: int = pydantic.Field()
    """
    Size of the uploaded file in bytes
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
