# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import datetime as dt
import typing
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class HealthResponse(UniversalBaseModel):
    """
    Health check response
    """

    status: str = pydantic.Field()
    """
    Overall health status
    """

    timestamp: dt.datetime = pydantic.Field()
    """
    Current server timestamp
    """

    components: typing.Optional[typing.Dict[str, str]] = pydantic.Field(default=None)
    """
    Health status of individual components
    """

    version: str = pydantic.Field()
    """
    API version
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
