# This file was auto-generated by Fern from our API Definition.

import typing

SandboxState = typing.Union[
    typing.Literal[
        "pending", "starting", "running", "terminating", "stopped", "error", "unknown"
    ],
    typing.Any,
]
