# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .sandbox import Sandbox
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class SandboxList(UniversalBaseModel):
    """
    Paginated list of sandboxes
    """

    items: typing.List[Sandbox]
    total: int = pydantic.Field()
    """
    Total number of sandboxes matching the filter
    """

    limit: int = pydantic.Field()
    """
    Maximum items per page
    """

    offset: int = pydantic.Field()
    """
    Number of items skipped
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
