# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
from .sandbox_state import SandboxState
import typing_extensions
import typing
from ..core.serialization import FieldMetadata
import datetime as dt
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class Sandbox(UniversalBaseModel):
    """
    A sandbox instance
    """

    id: str = pydantic.Field()
    """
    Unique identifier of the sandbox
    """

    name: str = pydantic.Field()
    """
    Human-readable name of the sandbox
    """

    state: SandboxState
    desired_state: typing_extensions.Annotated[
        typing.Optional[SandboxState], FieldMetadata(alias="desiredState")
    ] = None
    env: typing.Dict[str, str] = pydantic.Field()
    """
    Environment variables set in the sandbox
    """

    labels: typing.Dict[str, str] = pydantic.Field()
    """
    Labels attached to the sandbox
    """

    error_reason: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="errorReason")
    ] = pydantic.Field(default=None)
    """
    Error message if the sandbox is in error state
    """

    created_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="createdAt")
    ] = pydantic.Field()
    """
    Timestamp when the sandbox was created
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
