# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class UploadUrlResponse(UniversalBaseModel):
    """
    Response containing presigned upload URL
    """

    upload_url: str = pydantic.Field()
    """
    Presigned URL to upload the file to
    """

    upload_id: str = pydantic.Field()
    """
    Unique identifier for this upload session
    """

    expires_in: int = pydantic.Field()
    """
    Seconds until the presigned URL expires
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
