/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "../../../../environments.mjs";
import * as core from "../../../../core/index.mjs";
import * as Isola from "../../../index.mjs";
export declare namespace Health {
    interface Options {
        environment?: core.Supplier<environments.IsolaEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey?: core.Supplier<string | undefined>;
    }
    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}
/**
 * Health and readiness endpoints
 */
export declare class Health {
    protected readonly _options: Health.Options;
    constructor(_options?: Health.Options);
    /**
     * Returns the health status of the gateway and its components
     *
     * @param {Health.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.health.check()
     */
    check(requestOptions?: Health.RequestOptions): core.HttpResponsePromise<Isola.HealthResponse>;
    private __check;
    /**
     * Returns whether the service is ready to accept requests
     *
     * @param {Health.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.health.readinessCheck()
     */
    readinessCheck(requestOptions?: Health.RequestOptions): core.HttpResponsePromise<Isola.ReadyResponse>;
    private __readinessCheck;
    protected _getCustomAuthorizationHeaders(): Promise<{
        "X-API-Key": string | undefined;
    }>;
}
