apiVersion: v1
kind: Service
metadata:
  name: isola-gw
  labels:
    app: isola-gw
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "isola-gw.selectorLabels" . | nindent 4 }}
---
{{- if .Values.nodePort.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: isola-gw-nodeport
  labels:
    app: isola-gw
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 8080
    name: http
  selector:
    {{- include "isola-gw.selectorLabels" . | nindent 4 }}
{{- end }}

