{{- if and .Values.storage.enabled .Values.storage.credentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "isola-gw.fullname" . }}-storage-credentials
  labels:
    app: isola-gw
type: Opaque
stringData:
  {{- if .Values.storage.credentials.awsAccessKeyId }}
  AWS_ACCESS_KEY_ID: {{ .Values.storage.credentials.awsAccessKeyId | quote }}
  {{- end }}
  {{- if .Values.storage.credentials.awsSecretAccessKey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.storage.credentials.awsSecretAccessKey | quote }}
  {{- end }}
{{- end }}
