apiVersion: v1
kind: Namespace
metadata:
  name: isola-sandboxes
  labels:
    app.kubernetes.io/name: isola-sandboxes
    app.kubernetes.io/instance: isola-sandboxes-dev
    app.kubernetes.io/version: dev
    app.kubernetes.io/component: sandbox-environment
    app.kubernetes.io/part-of: isola
#    app.kubernetes.io/managed-by: Helm