apiVersion: v1
kind: Service
metadata:
  name: isola-controller-nodeport
  labels:
    app.kubernetes.io/name: isola-controller
    app.kubernetes.io/instance: isola-controller-dev
    app.kubernetes.io/version: dev
    app.kubernetes.io/component: control-plane
    app.kubernetes.io/part-of: isola
    # app.kubernetes.io/managed-by: local-minikube
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: isola-controller
    app.kubernetes.io/instance: isola-controller-dev
  ports:
  - name: http-nodeport
    protocol: TCP
    port: 3000
    targetPort: http
    nodePort: 30080
