apiVersion: v1
kind: Namespace
metadata:
  name: isola-control-plane
  labels:
    app.kubernetes.io/name: isola-control-plane
    app.kubernetes.io/instance: isola-control-plane-dev
    app.kubernetes.io/version: dev
    app.kubernetes.io/component: control-plane
    app.kubernetes.io/part-of: isola
#    app.kubernetes.io/managed-by: Helm
