apiVersion: v1
kind: ServiceAccount
metadata:
  name: isola-controller-serviceaccount
  namespace: isola-control-plane
  labels:
    app.kubernetes.io/name: isola-controller
    app.kubernetes.io/part-of: isola