apiVersion: v1
kind: Service
metadata:
  name: isola-controller
  labels:
    app.kubernetes.io/name: isola-controller
    app.kubernetes.io/instance: isola-controller-dev
    app.kubernetes.io/version: dev
    app.kubernetes.io/component: control-plane
    app.kubernetes.io/part-of: isola
#    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: isola-controller
    app.kubernetes.io/instance: isola-controller-dev
  ports:
  - name: ws
    port: 8765
    targetPort: ws
    protocol: TCP
  - name: http
    port: 3000
    targetPort: http
    protocol: TCP
