/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "./environments.mjs";
import * as core from "./core/index.mjs";
import { Health } from "./api/resources/health/client/Client.mjs";
import { Sandboxes } from "./api/resources/sandboxes/client/Client.mjs";
import { Execution } from "./api/resources/execution/client/Client.mjs";
import { Files } from "./api/resources/files/client/Client.mjs";
export declare namespace IsolaClient {
    interface Options {
        environment?: core.Supplier<environments.IsolaEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey?: core.Supplier<string | undefined>;
    }
    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}
export declare class IsolaClient {
    protected readonly _options: IsolaClient.Options;
    protected _health: Health | undefined;
    protected _sandboxes: Sandboxes | undefined;
    protected _execution: Execution | undefined;
    protected _files: Files | undefined;
    constructor(_options?: IsolaClient.Options);
    get health(): Health;
    get sandboxes(): Sandboxes;
    get execution(): Execution;
    get files(): Files;
}
