/**
 * This file was auto-generated by Fern from our API Definition.
 */
import { Health } from "./api/resources/health/client/Client.mjs";
import { Sandboxes } from "./api/resources/sandboxes/client/Client.mjs";
import { Execution } from "./api/resources/execution/client/Client.mjs";
import { Files } from "./api/resources/files/client/Client.mjs";
export class IsolaClient {
    constructor(_options = {}) {
        this._options = _options;
    }
    get health() {
        var _a;
        return ((_a = this._health) !== null && _a !== void 0 ? _a : (this._health = new Health(this._options)));
    }
    get sandboxes() {
        var _a;
        return ((_a = this._sandboxes) !== null && _a !== void 0 ? _a : (this._sandboxes = new Sandboxes(this._options)));
    }
    get execution() {
        var _a;
        return ((_a = this._execution) !== null && _a !== void 0 ? _a : (this._execution = new Execution(this._options)));
    }
    get files() {
        var _a;
        return ((_a = this._files) !== null && _a !== void 0 ? _a : (this._files = new Files(this._options)));
    }
}
