/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare const IsolaEnvironment: {
    readonly Default: "http://localhost:8080";
};
export type IsolaEnvironment = typeof IsolaEnvironment.Default;
