/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as errors from "../../errors/index.js";
import * as Isola from "../index.js";
import * as core from "../../core/index.js";
export declare class UnauthorizedError extends errors.IsolaError {
    constructor(body: Isola.ErrorResponse, rawResponse?: core.RawResponse);
}
