# This file was auto-generated by Fern from our API Definition.

import typing
from ..core.client_wrapper import SyncClientWrapper
from ..types.sandbox_state import SandboxState
from ..core.request_options import RequestOptions
from ..types.sandbox_list import SandboxList
from ..core.pydantic_utilities import parse_obj_as
from ..errors.bad_request_error import BadRequestError
from ..types.error_response import ErrorResponse
from ..errors.unauthorized_error import UnauthorizedError
from ..errors.internal_server_error import InternalServerError
from json.decoder import JSONDecodeError
from ..core.api_error import ApiError
from ..types.attached_volume import AttachedVolume
from ..types.sandbox import Sandbox
from ..core.serialization import convert_and_respect_annotation_metadata
from ..core.jsonable_encoder import jsonable_encoder
from ..errors.not_found_error import NotFoundError
from ..core.client_wrapper import AsyncClientWrapper

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class SandboxesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_sandboxes(
        self,
        *,
        state: typing.Optional[SandboxState] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SandboxList:
        """
        Returns a paginated list of sandboxes, optionally filtered by state

        Parameters
        ----------
        state : typing.Optional[SandboxState]
            Filter by sandbox state

        limit : typing.Optional[int]
            Maximum number of sandboxes to return

        offset : typing.Optional[int]
            Number of sandboxes to skip

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SandboxList
            List of sandboxes

        Examples
        --------
        from isola import Isola

        client = Isola(
            api_key="YOUR_API_KEY",
        )
        client.sandboxes.list_sandboxes(
            state="pending",
            limit=1,
            offset=1,
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v1/sandboxes",
            method="GET",
            params={
                "state": state,
                "limit": limit,
                "offset": offset,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    SandboxList,
                    parse_obj_as(
                        type_=SandboxList,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def create_sandbox(
        self,
        *,
        name: str,
        image: typing.Optional[str] = OMIT,
        region: typing.Optional[str] = OMIT,
        cpu: typing.Optional[float] = OMIT,
        memory: typing.Optional[float] = OMIT,
        disk: typing.Optional[float] = OMIT,
        gpu: typing.Optional[int] = OMIT,
        env: typing.Optional[typing.Dict[str, str]] = OMIT,
        labels: typing.Optional[typing.Dict[str, str]] = OMIT,
        volumes: typing.Optional[typing.Sequence[AttachedVolume]] = OMIT,
        auto_start: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Sandbox:
        """
        Creates a new sandbox with the specified configuration

        Parameters
        ----------
        name : str
            Human-readable name for the sandbox

        image : typing.Optional[str]
            Container image to use for the sandbox

        region : typing.Optional[str]
            Region where the sandbox should be deployed

        cpu : typing.Optional[float]
            CPU cores to allocate (e.g., 0.5, 1, 2)

        memory : typing.Optional[float]
            Memory in GB to allocate

        disk : typing.Optional[float]
            Disk space in GB to allocate

        gpu : typing.Optional[int]
            Number of GPUs to allocate

        env : typing.Optional[typing.Dict[str, str]]
            Environment variables to set in the sandbox

        labels : typing.Optional[typing.Dict[str, str]]
            Labels to attach to the sandbox

        volumes : typing.Optional[typing.Sequence[AttachedVolume]]
            Volumes to attach to the sandbox

        auto_start : typing.Optional[bool]
            Whether to start the sandbox automatically after creation

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Sandbox
            Sandbox created successfully

        Examples
        --------
        from isola import Isola

        client = Isola(
            api_key="YOUR_API_KEY",
        )
        client.sandboxes.create_sandbox(
            name="name",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v1/sandboxes",
            method="POST",
            json={
                "name": name,
                "image": image,
                "region": region,
                "cpu": cpu,
                "memory": memory,
                "disk": disk,
                "gpu": gpu,
                "env": env,
                "labels": labels,
                "volumes": convert_and_respect_annotation_metadata(
                    object_=volumes,
                    annotation=typing.Sequence[AttachedVolume],
                    direction="write",
                ),
                "autoStart": auto_start,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    Sandbox,
                    parse_obj_as(
                        type_=Sandbox,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def get_sandbox(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> Sandbox:
        """
        Returns details of a specific sandbox by ID

        Parameters
        ----------
        id : str
            Unique identifier of the sandbox (UUID)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Sandbox
            Sandbox details

        Examples
        --------
        from isola import Isola

        client = Isola(
            api_key="YOUR_API_KEY",
        )
        client.sandboxes.get_sandbox(
            id="550e8400-e29b-41d4-a716-446655440000",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/sandboxes/{jsonable_encoder(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    Sandbox,
                    parse_obj_as(
                        type_=Sandbox,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def terminate_sandbox(
        self,
        id: str,
        *,
        force: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Terminates and deletes a sandbox

        Parameters
        ----------
        id : str
            Unique identifier of the sandbox (UUID)

        force : typing.Optional[bool]
            Force immediate termination without graceful shutdown

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from isola import Isola

        client = Isola(
            api_key="YOUR_API_KEY",
        )
        client.sandboxes.terminate_sandbox(
            id="550e8400-e29b-41d4-a716-446655440000",
            force=True,
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/sandboxes/{jsonable_encoder(id)}",
            method="DELETE",
            params={
                "force": force,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)


class AsyncSandboxesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_sandboxes(
        self,
        *,
        state: typing.Optional[SandboxState] = None,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SandboxList:
        """
        Returns a paginated list of sandboxes, optionally filtered by state

        Parameters
        ----------
        state : typing.Optional[SandboxState]
            Filter by sandbox state

        limit : typing.Optional[int]
            Maximum number of sandboxes to return

        offset : typing.Optional[int]
            Number of sandboxes to skip

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SandboxList
            List of sandboxes

        Examples
        --------
        import asyncio

        from isola import AsyncIsola

        client = AsyncIsola(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sandboxes.list_sandboxes(
                state="pending",
                limit=1,
                offset=1,
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v1/sandboxes",
            method="GET",
            params={
                "state": state,
                "limit": limit,
                "offset": offset,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    SandboxList,
                    parse_obj_as(
                        type_=SandboxList,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def create_sandbox(
        self,
        *,
        name: str,
        image: typing.Optional[str] = OMIT,
        region: typing.Optional[str] = OMIT,
        cpu: typing.Optional[float] = OMIT,
        memory: typing.Optional[float] = OMIT,
        disk: typing.Optional[float] = OMIT,
        gpu: typing.Optional[int] = OMIT,
        env: typing.Optional[typing.Dict[str, str]] = OMIT,
        labels: typing.Optional[typing.Dict[str, str]] = OMIT,
        volumes: typing.Optional[typing.Sequence[AttachedVolume]] = OMIT,
        auto_start: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Sandbox:
        """
        Creates a new sandbox with the specified configuration

        Parameters
        ----------
        name : str
            Human-readable name for the sandbox

        image : typing.Optional[str]
            Container image to use for the sandbox

        region : typing.Optional[str]
            Region where the sandbox should be deployed

        cpu : typing.Optional[float]
            CPU cores to allocate (e.g., 0.5, 1, 2)

        memory : typing.Optional[float]
            Memory in GB to allocate

        disk : typing.Optional[float]
            Disk space in GB to allocate

        gpu : typing.Optional[int]
            Number of GPUs to allocate

        env : typing.Optional[typing.Dict[str, str]]
            Environment variables to set in the sandbox

        labels : typing.Optional[typing.Dict[str, str]]
            Labels to attach to the sandbox

        volumes : typing.Optional[typing.Sequence[AttachedVolume]]
            Volumes to attach to the sandbox

        auto_start : typing.Optional[bool]
            Whether to start the sandbox automatically after creation

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Sandbox
            Sandbox created successfully

        Examples
        --------
        import asyncio

        from isola import AsyncIsola

        client = AsyncIsola(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sandboxes.create_sandbox(
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v1/sandboxes",
            method="POST",
            json={
                "name": name,
                "image": image,
                "region": region,
                "cpu": cpu,
                "memory": memory,
                "disk": disk,
                "gpu": gpu,
                "env": env,
                "labels": labels,
                "volumes": convert_and_respect_annotation_metadata(
                    object_=volumes,
                    annotation=typing.Sequence[AttachedVolume],
                    direction="write",
                ),
                "autoStart": auto_start,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    Sandbox,
                    parse_obj_as(
                        type_=Sandbox,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 400:
                raise BadRequestError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def get_sandbox(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> Sandbox:
        """
        Returns details of a specific sandbox by ID

        Parameters
        ----------
        id : str
            Unique identifier of the sandbox (UUID)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Sandbox
            Sandbox details

        Examples
        --------
        import asyncio

        from isola import AsyncIsola

        client = AsyncIsola(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sandboxes.get_sandbox(
                id="550e8400-e29b-41d4-a716-446655440000",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/sandboxes/{jsonable_encoder(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    Sandbox,
                    parse_obj_as(
                        type_=Sandbox,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def terminate_sandbox(
        self,
        id: str,
        *,
        force: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Terminates and deletes a sandbox

        Parameters
        ----------
        id : str
            Unique identifier of the sandbox (UUID)

        force : typing.Optional[bool]
            Force immediate termination without graceful shutdown

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from isola import AsyncIsola

        client = AsyncIsola(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.sandboxes.terminate_sandbox(
                id="550e8400-e29b-41d4-a716-446655440000",
                force=True,
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/sandboxes/{jsonable_encoder(id)}",
            method="DELETE",
            params={
                "force": force,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return
            if _response.status_code == 401:
                raise UnauthorizedError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    typing.cast(
                        ErrorResponse,
                        parse_obj_as(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    )
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)
