/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * A volume attached to the sandbox
 */
export interface AttachedVolume {
    /** ID of the volume to attach */
    volumeId: string;
    /** Path where the volume is mounted in the sandbox */
    mountPath: string;
}
