/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Error response
 */
export interface ErrorResponse {
    /** Error code */
    error: string;
    /** Human-readable error message */
    message: string;
    /** Additional error details */
    details?: Record<string, unknown>;
}
