/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Response from file upload
 */
export interface FileUploadResponse {
    /** Whether the upload was successful */
    success: boolean;
    /** Path where the file was uploaded */
    path: string;
    /** Size of the uploaded file in bytes */
    size: number;
}
