/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Health check response
 */
export interface HealthResponse {
    /** Overall health status */
    status: string;
    /** Current server timestamp */
    timestamp: string;
    /** Health status of individual components */
    components?: Record<string, string>;
    /** API version */
    version: string;
}
