/**
 * This file was auto-generated by Fern from our API Definition.
 */
export const SandboxState = {
    Pending: "pending",
    Starting: "starting",
    Running: "running",
    Terminating: "terminating",
    Stopped: "stopped",
    Error: "error",
    Unknown: "unknown",
};
