/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Isola from "../index.mjs";
/**
 * A sandbox instance
 */
export interface Sandbox {
    /** Unique identifier of the sandbox */
    id: string;
    /** Human-readable name of the sandbox */
    name: string;
    state: Isola.SandboxState;
    desiredState?: Isola.SandboxState;
    /** Environment variables set in the sandbox */
    env: Record<string, string>;
    /** Labels attached to the sandbox */
    labels: Record<string, string>;
    /** Error message if the sandbox is in error state */
    errorReason?: string;
    /** Timestamp when the sandbox was created */
    createdAt: string;
}
