apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: isola-platform-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: isola
  
  source:
    repoURL: https://github.com/omereli/dev-isola.git
    targetRevision: HEAD
    path: charts/isola-platform
    helm:
      valueFiles:
        - values.yaml
        - values-dev.yaml
      parameters:
      - name: "global.environment"
        value: "dev"
  
  destination:
    server: https://kubernetes.default.svc
    namespace: isola-control-plane
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  revisionHistoryLimit: 10
