apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: isola-controller
  namespace: isola-sandboxes
  labels:
    app: isola-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: isola-controller
subjects:
- kind: ServiceAccount
  name: isola-controller
  namespace: {{ .Release.Namespace }}
