apiVersion: v1
kind: Service
metadata:
  name: isola-controller
  labels:
    app: isola-controller
spec:
  type: ClusterIP
  ports:
  - port: 30080
    targetPort: http
    protocol: TCP
    name: http
  - port: 8765
    targetPort: ws
    protocol: TCP
    name: websocket
  selector:
    {{- include "isola-controller.selectorLabels" . | nindent 4 }}
---
{{- if .Values.nodePort.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: isola-controller-nodeport
  labels:
    app: isola-controller
spec:
  type: NodePort
  ports:
  - port: 30080
    targetPort: 30080
    nodePort: 30080
    name: http
  selector:
    {{- include "isola-controller.selectorLabels" . | nindent 4 }}
{{- end }}
