/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         upload_id: "upload_id",
 *         filename: "filename",
 *         path: "path"
 *     }
 */
export interface ConfirmUploadRequest {
    /** Upload ID from the upload-url response */
    upload_id: string;
    /** Name of the uploaded file */
    filename: string;
    /** Target path in the sandbox */
    path: string;
}
