/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         path: "/home/user/large-file.zip",
 *         filename: "large-file.zip"
 *     }
 */
export interface UploadUrlRequest {
    /** Target path in the sandbox where the file will be placed */
    path: string;
    /** Name of the file being uploaded */
    filename: string;
    /** MIME type of the file */
    content_type?: string;
}
