apiVersion: sandbox.isola.run/v1alpha1
kind: SandboxTemplate
metadata:
  labels:
    app.kubernetes.io/name: isola-operator
    app.kubernetes.io/managed-by: kustomize
  name: sandboxtemplate-sample
spec:
  # TODO(user): Add fields here
