{{- if .Values.identitySigner.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "isola.identitySigner.fullname" . }}
  labels:
    {{- include "isola.identitySigner.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "isola.identitySigner.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "isola.identitySigner.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
