{{- if and .Values.identitySigner.enabled .Values.identitySigner.sandboxServiceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "isola.sandbox.serviceAccountName" . }}
  namespace: {{ include "isola.sandboxNamespace" . }}
  labels:
    {{- include "isola.identitySigner.labels" . | nindent 4 }}
{{- end }}
