{{- if and .Values.identitySigner.enabled .Values.identitySigner.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "isola.identitySigner.serviceAccountName" . }}
  labels:
    {{- include "isola.identitySigner.labels" . | nindent 4 }}
  {{- with .Values.identitySigner.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
