---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: isola-operator-manager-role
rules:
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sandbox.isola.run
  resources:
  - networktemplates
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sandbox.isola.run
  resources:
  - networktemplates/finalizers
  verbs:
  - update
- apiGroups:
  - sandbox.isola.run
  resources:
  - networktemplates/status
  verbs:
  - get
  - patch
  - update
