/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Isola from "../../../../index.js";
/**
 * @example
 *     {
 *         state: "pending",
 *         limit: 1,
 *         offset: 1
 *     }
 */
export interface ListSandboxesRequest {
    /**
     * Filter by sandbox state
     */
    state?: Isola.SandboxState;
    /**
     * Maximum number of sandboxes to return
     */
    limit?: number;
    /**
     * Number of sandboxes to skip
     */
    offset?: number;
}
