/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * @example
 *     {
 *         force: true
 *     }
 */
export interface TerminateSandboxRequest {
    /**
     * Force immediate termination without graceful shutdown
     */
    force?: boolean;
}
