/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "../../../../environments.mjs";
import * as core from "../../../../core/index.mjs";
import * as Isola from "../../../index.mjs";
export declare namespace Execution {
    interface Options {
        environment?: core.Supplier<environments.IsolaEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey?: core.Supplier<string | undefined>;
    }
    interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional headers to include in the request. */
        headers?: Record<string, string>;
    }
}
/**
 * Command execution in sandboxes
 */
export declare class Execution {
    protected readonly _options: Execution.Options;
    constructor(_options?: Execution.Options);
    /**
     * Executes a shell command in the sandbox and returns the output.
     * The sandbox must be in 'running' state.
     *
     * @param {string} id - Unique identifier of the sandbox (UUID)
     * @param {Isola.ExecuteCommandRequest} request
     * @param {Execution.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Isola.BadRequestError}
     * @throws {@link Isola.UnauthorizedError}
     * @throws {@link Isola.NotFoundError}
     * @throws {@link Isola.ConflictError}
     * @throws {@link Isola.InternalServerError}
     *
     * @example
     *     await client.execution.executeCommand("550e8400-e29b-41d4-a716-446655440000", {
     *         command: "python script.py"
     *     })
     */
    executeCommand(id: string, request: Isola.ExecuteCommandRequest, requestOptions?: Execution.RequestOptions): core.HttpResponsePromise<Isola.ExecuteCommandResponse>;
    private __executeCommand;
    protected _getCustomAuthorizationHeaders(): Promise<{
        "X-API-Key": string | undefined;
    }>;
}
