/**
 * This file was auto-generated by Fern from our API Definition.
 */
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
import * as environments from "../../../../environments.mjs";
import * as core from "../../../../core/index.mjs";
import * as Isola from "../../../index.mjs";
import urlJoin from "url-join";
import * as errors from "../../../../errors/index.mjs";
/**
 * Command execution in sandboxes
 */
export class Execution {
    constructor(_options = {}) {
        this._options = _options;
    }
    /**
     * Executes a shell command in the sandbox and returns the output.
     * The sandbox must be in 'running' state.
     *
     * @param {string} id - Unique identifier of the sandbox (UUID)
     * @param {Isola.ExecuteCommandRequest} request
     * @param {Execution.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Isola.BadRequestError}
     * @throws {@link Isola.UnauthorizedError}
     * @throws {@link Isola.NotFoundError}
     * @throws {@link Isola.ConflictError}
     * @throws {@link Isola.InternalServerError}
     *
     * @example
     *     await client.execution.executeCommand("550e8400-e29b-41d4-a716-446655440000", {
     *         command: "python script.py"
     *     })
     */
    executeCommand(id, request, requestOptions) {
        return core.HttpResponsePromise.fromPromise(this.__executeCommand(id, request, requestOptions));
    }
    __executeCommand(id, request, requestOptions) {
        return __awaiter(this, void 0, void 0, function* () {
            var _a, _b;
            const _response = yield core.fetcher({
                url: urlJoin((_b = (_a = (yield core.Supplier.get(this._options.baseUrl))) !== null && _a !== void 0 ? _a : (yield core.Supplier.get(this._options.environment))) !== null && _b !== void 0 ? _b : environments.IsolaEnvironment.Default, `api/v1/sandboxes/${encodeURIComponent(id)}/execute`),
                method: "POST",
                headers: Object.assign(Object.assign({ "X-Fern-Language": "JavaScript", "X-Fern-Runtime": core.RUNTIME.type, "X-Fern-Runtime-Version": core.RUNTIME.version }, (yield this._getCustomAuthorizationHeaders())), requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.headers),
                contentType: "application/json",
                requestType: "json",
                body: request,
                timeoutMs: (requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.timeoutInSeconds) != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                maxRetries: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.maxRetries,
                abortSignal: requestOptions === null || requestOptions === void 0 ? void 0 : requestOptions.abortSignal,
            });
            if (_response.ok) {
                return { data: _response.body, rawResponse: _response.rawResponse };
            }
            if (_response.error.reason === "status-code") {
                switch (_response.error.statusCode) {
                    case 400:
                        throw new Isola.BadRequestError(_response.error.body, _response.rawResponse);
                    case 401:
                        throw new Isola.UnauthorizedError(_response.error.body, _response.rawResponse);
                    case 404:
                        throw new Isola.NotFoundError(_response.error.body, _response.rawResponse);
                    case 409:
                        throw new Isola.ConflictError(_response.error.body, _response.rawResponse);
                    case 500:
                        throw new Isola.InternalServerError(_response.error.body, _response.rawResponse);
                    default:
                        throw new errors.IsolaError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.body,
                            rawResponse: _response.rawResponse,
                        });
                }
            }
            switch (_response.error.reason) {
                case "non-json":
                    throw new errors.IsolaError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.rawBody,
                        rawResponse: _response.rawResponse,
                    });
                case "timeout":
                    throw new errors.IsolaTimeoutError("Timeout exceeded when calling POST /api/v1/sandboxes/{id}/execute.");
                case "unknown":
                    throw new errors.IsolaError({
                        message: _response.error.errorMessage,
                        rawResponse: _response.rawResponse,
                    });
            }
        });
    }
    _getCustomAuthorizationHeaders() {
        return __awaiter(this, void 0, void 0, function* () {
            const apiKeyValue = yield core.Supplier.get(this._options.apiKey);
            return { "X-API-Key": apiKeyValue };
        });
    }
}
