# Development values - used by Tilt for local development

operator:
  image:
    registry: ""
    repository: isola-operator
    tag: "dev"
    pullPolicy: IfNotPresent

  sandboxSidecar:
    image:
      registry: ""
      repository: sandbox-sidecar
      tag: "dev"

  logging:
    level: debug
    devMode: true

  sandboxRuntime:
    type: gvisor # alternatively, if gvisor not installed, use clusterDefault

    gvisor:
      runtimeClassName: gvisor
      rootfssnapshot:
        enabled: true
        runsc:
          binaryPath: /usr/local/bin/runsc
          rootDir: /run/containerd/runsc/k8s.io
        uploader:
          image:
            registry: ""
            repository: isola-uploader
            tag: "dev"

        storage:
          type: s3
          s3:
            bucket: isola-snapshots
            region: us-east-1
            endpoint: "http://localstack.localstack.svc.cluster.local:4566"
            forcePathStyle: true
            accessKeyId: "test"
            secretAccessKey: "test"

        snapshotMounter:
          hostMountPath: /mnt/isola-snapshots
          rclone:
            image:
              registry: docker.io
              repository: rclone/rclone
              tag: "1.73.2"
            dirCacheTime: "2s"
          mounter:
            image:
              registry: ""
              repository: snapshot-mounter
              tag: "dev"

apiGateway:
  image:
    registry: ""
    repository: api-gateway
    tag: "dev"
    pullPolicy: IfNotPresent

  logging:
    level: debug
    devMode: true

  service:
    type: NodePort
    nodePort: 30080
