name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run go mod tidy
        run: go mod tidy

      - name: Run tests
        run: |
          go install sigs.k8s.io/controller-runtime/tools/setup-envtest@v0.23.0
          make test
