{{- if .Values.snapshot.storage.credentialSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.snapshot.storage.credentialSecret.name }}
  namespace: {{ .Values.sandboxNamespace }}
  labels:
    {{- include "isola-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.snapshot.storage.credentialSecret.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
